rules:
  extends-before-mixins: 2
  extends-before-declarations: 2
  placeholder-in-extend: 0
  hex-notation: 2
  indentation: 2
  property-sort-order: 2
  variable-for-property: 2
  no-color-literals: 2
  clean-import-paths: 2
  hex-length: 2
  force-pseudo-nesting: 2
  force-element-nesting: 2
  quotes: 2
  class-name-format: 0
  empty-line-between-blocks: 2
  leading-zero: 2
  space-before-brace: 2
  space-before-bang: 2
  no-important: 0
  no-css-comments: 2
  no-color-keywords: 2
  space-after-colon: 2
  no-vendor-prefixes: 0
  border-zero: 2
  no-empty-rulesets: 2
  trailing-semicolon: 2
  no-duplicate-properties: 2
  shorthand-values: 2
  pseudo-element: 2
  single-line-per-selector: 2
  zero-unit: 2
  no-mergeable-selectors: 2
  no-qualifying-elements: 2
